apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-general
  namespace: default
  annotations: 
    kubed.appscode.com/sync: "cicd=kubed"
spec:
  encryptedData:
    token: AgB5zmmcw9Ye7r6d+TR0xf5Gp7FH6hhQKjQpiQXvmzkuAO0ANSfgTqF6yoahfUHXr7DeShhnv8e1UB8GUVpXeusEKmxLrJiX1ld16RZZNYQz+HtvG7RJ9KXC4OWbCcCbEP8JmcdQnhbJF20B1H3CdZ+OLvF44JUy/pHO+hVaUkSm8oFfxYMhLgZCyoJTJEBP5RUzoxQYKWjgsyFljYNSVF/AONggEjLy8CDdlANeipnJqJfj2OK17QAEBlyfY3rW+6DRH8X5hcHlKsWec9ZatgY51Y8/YeLz2Zw3hkdCxw+ujasF4iXtlRKtXgz84EuD0vZHUWtyBce/bKLuOphg+paU1EqPQYYGqigkBvXGXu29zFaCtc6TljHmHTz5EIgd2XTnFNNh81lmPej8Fmb0dajoURRKyYVg6aW8CVc73jiFhnW7hkVT7kFd1oxeftByYeUQBI3rNXa8YzI6Bvu1sEi1jbwGOGgz4zmYkKlq6KfmUOIaK67e0CTJFZpbDGk9ruKUjE3vJxxiD67Qg8YepZfHVyDjDqlFbZrxJpo6Y9JzpDfgTqjsa52tS6Ficmx+Bs3iRcavCUdFkl+scd7t0E0M4dFNOKtwXTGv2ot0C8vitH1h2JkzOn5Gi5/Gnxg+SZjBm03RJ/zbOLt43JesjQNER0expS026EudMil0oRxkc1sPTP6l4VHrV2wh9aW8pSHLCHhI2/ZtY1urQRuxNV/HZQPlc9Gso+vUDixCRmZu8xBmjzfst39H
    username: AgCxZvuc33EFe3SB2mI8Kx6yg86xAQfZ/cv/rd9gYuLw1LBX56eVZOSGuE7BCmpZy+P3cuRBMyvpYCQeJ1cTBVOEsx+QePBn5cGDDFPaefMJeC0KON9Ubj004gQ/9cgOcsHJ7l6qOE3hnBpPVenilT/Be52YkcJFAhbIMBjihpGZ2/9OLo1253dS+JMVxysc+j+1J/b71S8qUwtWT0IpWZNIKUEA5egbshEXypnlBbym/ZyNxdA0mXVWHdo4WZFCVf7YbmPiZUF9dICn3hTnnOLCDKoe7a3i5NfPW6kmJwWa9pZosJ6hva8OUCUXE9h2klEYkzF1PLM+dSHSbgDRSeao9oXr+9csUJXKD/idsjKrs/iHX4/rETAzJQIRgH/2Q7ug0LHPqfYMrTYwo5pzgi37n/qo7X9byQLCn9YQhUY4jsK8dEiVZtjgppI+8ukJqaTr3Zp/CuOruGNXsJb7BOq12pfPjzMd79FCXRs6tfMl5lip3OVhey4IrHHDuELBAFA0BWkX1yf/XGereBFM6UmsWeqqViRlX5tfj+YVoinYgyTS0jvR58jNCFLzFR8FV2ziiXAZBBXjwp2LwoyMbdpl8Ch+Sw0RhdmVjPXP6zPMz/8VVVSP6fDiAQFAXg3gbeltxfffEbODWse8C85PXeFZaZy7WVggQ/xFCS0NGQpwoGqY/JBLxs6NsTRZ5xIP/CVg3gHE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea-general
      namespace: default

