kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config # "paths":["/var/local-path-provisioner"]
  namespace: local-path-storage
data:
  config.json: |-
    {
            "nodePathMap":[
            {
                    "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                    "paths":["/var/mnt/extra"]
            }
            ]
    }