apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo
resources:
- namespace.yaml
- github.com/argoproj/argo-workflows/manifests/cluster-install?ref=v3.3.3
- ingress.yaml
images:
- name: quay.io/argoproj/argocli
  newTag: v3.3.3
patchesStrategicMerge:
- config.yaml
# - argo-role-binding.yaml
# - argo-server-role-binding.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: argo-server
  path: argo-server-patch.yaml

  