apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: device-connector-workflow
  namespace: workflows
spec:
  entrypoint: pipeline
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  # volumeClaimTemplates:
  # - metadata:
  #     name: maven-repo
  #   spec:
  #     storageClassName: local-path
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 10Gi
  volumes:
  - name: dind-storage
    emptyDir: {}
  - name: dind-socket
    emptyDir: {}
  - name: maven-repo
    emptyDir: {}
    # persistentVolumeClaim:
    #   claimName: maven-artifact-pvc
  - name: kaniko-secret
    secret:
      secretName: harbor-core-secret #dockerhub-secret
      items:
        - key: .dockerconfigjson
          path: config.json
  templates:
  - name: pipeline
    dag:
      tasks:
      - name: build-image-hono
        templateRef:
          name: build-image
          template: build-kaniko-git
          clusterScope: true
        arguments:
          parameters:
            # - name: app_repo
            #   value: http://gitea-http.gitea.svc.cluster.local:3000/root/device-homeomorphisx.git
            - name: service
              value: hono-service
            - name: container_image
              value: harbor-core.harbor-system.svc.cluster.local/library/hono-service
            - name: container_tag
              value: 0.1-SNAPSHOT
