apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-events
bases:
- github.com/argoproj/argo-events/manifests/cluster-install?ref=v1.6.3
resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-events/v1.6.3/manifests/install-validating-webhook.yaml
