apiVersion: v1
data:
  password: NjRmYzc2ZjBiOWEwZTAzOTQzNGQ5ZTMyMmZlZTZhNDg1ZmZhNGE3Yg==
  type: Z2l0
  url: aHR0cDovL2dpdGVhLWh0dHAuZ2l0ZWEuc3ZjLmNsdXN0ZXIubG9jYWw6MzAwMC9yb290
  username: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: null
  name: gitea-argocd
