apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workflows
resources:
- maven-artifact-pvc.yaml
- clusterworkflowtemplate/java-compiletest-with-sidecar.yaml
- clusterworkflowtemplate/java-package.yaml
- clusterworkflowtemplate/build-image.yaml
#- workflowtemplate/device-connector-workflow.yaml
- workflowtemplate/tmp.yaml
#- workflowtemplate/only.yaml