apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: system
  source:
    path: 01-metallb
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/root/cloud-system-deployment.git
    targetRevision: HEAD
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
