apiVersion: v1
kind: Secret
metadata:
  name: system-gitops
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: http://gitea-http.gitea.svc.cluster.local:3000/root/cloud-system-deployment.git

